// Chapter line --------------------------------//
== Background Knowledge

=== Accelerometer
    x = accel_filtered.x;
    y = accel_filtered.y;
    z = accel_filtered.z;

    accel_angles.x = atan2(y, z) * RAD_TO_DEG;
    accel_angles.y = atan2(-1 * x, sqrt(y * y + z * z)) * RAD_TO_DEG;

=== AHRS
    Attitude and heading reference system，姿态和航向参照系统；
    Ardupilot 使用DCM或者EKF算法;
    參考：
    https://github.com/pronenewbits/Arduino_AHRS_System
=== Arduino
    开发工具

=== Ardupilot
    飞控系统

=== Barometer
    气压表，用于测量高度；

=== Brushless Motor
    无刷电机

=== CAN
    更长距离通讯，快，多主，3/4针引脚；
    
=== COM

=== Copter
    旋翼无人机，参考：https://ardupilot.org/copter/docs/what-you-need.html

=== DCM
    余弦向量矩阵算法，
    参考：
    https://github.com/alrevuelta/dcm-algorithm-cpp/tree/master
    Doug Weibel, Jordi Munoz and Jose Julio. DIYDrones.com
    http://www.starlino.com/dcm_tutorial.html

=== DSM
    Spektrum/DSM is a 115200 baud UART protocol. 

=== ECU

=== ESC（Electronic Speed Controls）
    外设，电调
    参考：
    https://ardupilot.org/copter/docs/common-escs-and-motors.html
    ESC接地和联线问题注意事项：
    https://ardupilot.org/copter/docs/common-esc-grounding.html

=== ESP32

=== FMU
=== GCS
    地面站，可选配置，建议配置；
    地面站通过遥测(Telemetry)和无人机通讯；
    Mission Planner is the most full-featured GCS.
    APM Planner 2.0 is the best one on MAC/Linux.
    MAVProxy is on linux and used for developer.
    QGroundControl is on any platform.

=== Gyroscope
    
    //rotational rates = degrees per second
    unit32_t gyro_last_update = micros();
    void compute_gyro_angles() {
        mpu6050_read_gyro(&gyro_rates);
        rates.x = gyro_rates.x + GYRO_X_OFFSET;
        delta_t = (micros() - gyro_last_update) / (1000 * 1000);
        gyro_angles.x += rates.x * delta_t;
    }

    参考：
    https://www.youtube.com/watch?v=CHSYgLfhwUo&t=1200s
=== HRT (high resolution timer)

=== I2C
    通讯协议，短距离（1m)，主从结构，一主多从，需要4针引脚，慢；
    可用于接入指南针；

=== IMM
    Filter for Object tracking,
    參考：
    https://www.youtube.com/watch?v=hJG08iWlres

=== IMU
    Inertial measurement unit，惯性测量单元，包括了加速度计和陀螺仪；

    參考：
    https://www.youtube.com/watch?v=CHSYgLfhwUo&t=1200s
    https://ww2.mathworks.cn/help/fusion/ug/Estimating-Orientation-Using-Inertial-Sensor-Fusion-and-MPU-9250.html


=== Kalman filter
    卡尔曼滤波，用于AP高度预测？

    參考：
    https://www.bitcraze.io/documentation/repository/crazyflie-firmware/master/functional-areas/sensor-to-control/state_estimators/

    https://github.com/pronenewbits/Embedded_EKF_Library
    https://github.com/pronenewbits/Arduino_AHRS_System

    https://idsc.ethz.ch/education/lectures/recursive-estimation.html

=== MARG
    Magnetic angular rate and gravity

=== MAVLink
    二进制的遥测协议；
    参考：
    https://mavlink.io/en/about/overview.html
    最多16个通道；

=== MMA
    Mixing Motor Algorithm
    roll,pitch,yam,thrust as the input.
    

=== MPU
    
=== OTG

=== Peripheral Hardware
    参考：
    https://ardupilot.org/copter/docs/common-optional-hardware.html
=== PID
    Proportional-Integral-Derivative；
    PID控制器的比例单元（P）、积分单元（I）和微分单元（D）分别对应目前误差、过去累计误差及未来误差。     
    参考：
    https://microdynamics.github.io/
=== Posix IO


=== PWM
    PWM（Pulse Width Modulation）是一种方波控制信号，用于输出和模拟"模拟信号"；
    如果主板提供了支持PWM的引脚，那么可以直接输出一个模拟信号到此类引脚；
    或者手动制造方波，输出到任一引脚；
    参考：
    https://blog.csdn.net/xq151750111/article/details/114551852

=== RC
    遥控

=== RTL

=== ROS

=== SBUS
    SBUS is a 100kbaud inverted UART protocol; 

=== SOC

=== SPI
    通讯协议，一主一从，快，短距离（10cm），5针引脚；
=== Serial/UART
    一主一从，长距离，较快，4/6针引脚；
=== Schematics
    电路图，Ardupilot 支持的一些主板，请参考：
    https://ardupilot.org/copter/docs/common-autopilots.html

    某些主板的设计在这里：
    https://github.com/ArduPilot/Schematics
    
=== UAV
    无人机


=== UART
    通用异步收发协议；
    最常用的设备间通讯协议；
    使用两个线TX(Transmitter)、TR(Receiver)分别作为发送和接受信号；
    Arduino主板的USB一般是通过UART作为电脑和单片机的通讯手段；
       参考：
    https://docs.arduino.cc/tutorials/nano-every/run-4-uart

=== WROOM
