
== {counter:chapter}. Dependencies
This section introduce the external tools and libs.

=== {chapter}.{counter:dep}. Environment

==== {chapter}.{dep}.{counter:tools}. MSYS2[mandatory] 

MSYS2 provide a easier package manager pacman for us to manage the necessary dev tools.

==== {chapter}.{dep}.{counter:tools}. UCRT64[mandatory] 
Unified C Run Time for building the code for windows platform.
[source,shell]
----
$ pacman -S ... 
----

=== {chapter}.{counter:dep}. Tools mandatory

==== {chapter}.{dep}.{counter:tools}. PlatformIO[mandatory]
We rely on platformIO to build this project. File platformio.ini is the entry point to build code. Following command builds the firmware for the target environment.

How to install pio?

Run pio to build.
[source,shell]
----
$ pio run -e arduino_uno_minima
----

=== {chapter}.{counter:dep}. Libs

==== {chapter}.{dep}.{counter:libs}. FreeRTOS

==== {chapter}.{dep}.{counter:libs}. JSBSim-Kernel

==== {chapter}.{dep}.{counter:libs}. ncurses

==== {chapter}.{dep}.{counter:libs}. pdcurses
This lib is needed to build the cdk source code.
[source,shell]
----
$ pacman -S mingw-w64-ucrt-x86_64-pdcurses
----
==== {chapter}.{dep}.{counter:libs}. CDK(curses development kit)
Download the source code from `site`.

Unzip the tar.

Build the code.

[source,shell]
----

$ ./configure.
configure: loading site script /etc/config.site
checking build system type... x86_64-w64-mingw32
...
$ make
/bin/sh ./gen-scale.sh DSCALE DScale Double double ./include/gen-scale.h >include/dscale.h
... 
$ make install
... 
Installing CDK header files in /ucrt64/include/cdk...
...
rm -f /ucrt64/include/cdk.h && mv /ucrt64/include/cdk/cdk.h /ucrt64/include/cdk.h
Installing CDK library
Installing script cdk5-config

----
=== {chapter}.{counter:dep}. Tools recommended

==== {chapter}.{dep}.{counter:tools2}. JSBSim
This tool is used to simulate and tuning the FCS under development.

==== {chapter}.{dep}.{counter:tools2}. Flight gear
This tool is used to simulate and tuning the FCS under development.

==== {chapter}.{dep}.{counter:tools2}. gnuplot

This tool is optional and is used to plot data and tuning FCS.

How to install gnuplot?

[source,shell]
----
pacman -S ...
----

==== {chapter}.{dep}.{counter:tools2}. JSBSim-Plot

The code under folder lib/JSBSim-Plot is come from the git repository.

This tool automatically process and call gnuplot to plot data produced by JSBSim.

To build the executable file use following command.You may need copy and rename the executable file .pio/build/plot/program with any path you like.

[source,shell]
----
$ pio run -e plot
$ cp .pio/build/plot/program.exe /usr/local/bin/prep_plot
----

This tool is used to organize the command line options and the call the gnuplot command to plot CSV data.

Firstly it can list the title names and the indexes of each title in a CSV data file.

[source,shell]
----
$ prep_plot data_log/qc2309.csv
Known variable names in data file:
  1:  Time
  2:  q bar (psf)
  ... 
  30:  Altitude ASL (ft)
  31:  Altitude AGL (ft)
  32:  Phi (deg)
  33:  Theta (deg)
  34:  Psi (deg)
  ...
----

Secondly we need to create a xml file as the instruction for the prep_plot to work with.

[source,shell]
----
$ 
----

[source,shell]
----
$ cat simulation/plot.sh
#!/bin/tcsh
 foreach file (*.csv)
   echo "process file:$file"
   if(-f data_plot/${file}.r.xml) prep_plot $file --plot=data_plot/${file}.r.xml | gnuplot
 end
 gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=output.pdf *.ps 
----

==== {chapter}.{dep}.{counter:tools2}. vscode IDE

This tool is optional and only needed in case you need an IDE to modify the code.

How to install vscode?

How to update the IntelliSense settings according to the platformio.ini configuration file?
Following command will update the file `.vscode/c_cpp_properties.json` for the environment fc_native;

[source,shell]
----
$ pio project init --ide vscode --environment fc_native
----

== {counter:chapter}. Code structure

=== {chapter}.{counter:arch}. Diagram
A diagram to illustrate the dependence relation between parts of code.


=== {chapter}.{counter:arch}. Folder structure

==== {chapter}.{arch}.{counter:folder}. lib/util
Utility code which itself does not have any dependence.

It's the kernel of the project.

==== {chapter}.{arch}.{counter:folder}. lib/hal
Hardware abstract layer.

In order to minimize the external dependence this layer take the role of isolating the core code from the external env. 

Note the code below has defined a global variable with type System. System is the interface to access external env. 

[source,cpp]
----
//file:lib/hal/include/a8/hal.h
namespace a8::hal {
    extern System *S;
}
----

In each environment's application layer, you should provide the initialization the S variable. For example the code below is for arduino env.

[source,cpp]
----
#include "a8/hal.h"
System * a8::hal::S = new ArduinoSystem();
----

==== {chapter}.{arch}.{counter:folder}. lib/

==== {chapter}.{arch}.{counter:folder}. lib/fc

Flight control of a quad copter.

Have two external dependence, lib/util and lib/hal.

==== {chapter}.{counter:folder}. lib/hal_arduino

Env of the real world supported by arduino framework. Here we mix all external stuff such as Arduino UNO R4, MPU9250 and so on.

This part of code depends on lib/util.

Should not depend on lib/core, but currently not meet this rule. We should minimize such dependence and finally remove all such code into the src/arduino folder. Finally it should be serval lines of such code and all env related code should become some form of configuration.

==== {chapter}.{arch}.{counter:folder}. lib/hal_native
End of simulation with all necessary external stuff such as JSBSim, Flight Gear etc.

Depends on lib/util.

Should not depend on lib/core, but currently not meet this rule.

==== {chapter}.{arch}.{counter:folder}. lib/FreeRTOS-Kernel
Do not edit the source code in this folder because all the code are from FreeRTOS official git repository.

This folder contains only the core code of FreeRTOS functions. We are using the thread/task and timer part of FreeRTOS.

You know the kernel part of FreeRTOS must be configured before it's application to concrete project. Actually you must provide a header file(FreeRTOSConfig.h) and set arguments by C language's preprocessing instructions. 

For example the below parameter is defined in the file of FreeRTOSConfig.h located in the lib/arduino/include folder.

Please note this folder cannot be compiled unless the additional header files for the target environment are provided. For mingw env, please find them from the folder of FreeRTOS-Kernel-MingW.

[source,c++]
----
#define configNUM_THREAD_LOCAL_STORAGE_POINTERS (5)
----

==== {chapter}.{arch}.{counter:folder}. lib/FreeRTOS-Kernel-MingW

Do not edit the source code in this folder because all the code are from FreeRTOS official git repository.

In order to compile FreeRTOS kernel with the native(MingW) environment we need following 3 parts of code.

*** heap4
This folder contains one of the memory management policy which we adopted for both Arduino UNO and native environment. This is enabled by the settings of environment of uno_r4_minima in the platformIO configuration file 'platformio.ini'.

Why we don't use the Arduino_FreeRTOS.h which provided by the arduino-renesas framework itself? It's because we are trying to get the code structure clean, clear and then easy understandable. So we need the code independent with each part and as less as possible to depend 3rd party code or library.

*** port.c


*** config

==== {chapter}.{arch}.{counter:folder}. lib/FreeRTOS-ArduinoRenesas-UNO
Do not edit the source code in this folder because all the code are from FreeRTOS official git repository.

For the purpose of porting FreeRTOS to the arduino_uno_minima environment.

==== {chapter}.{arch}.{counter:folder}. src
This folder contains the main function for each environment. How to distinguish them? It's is by the building filter which is defined in the platformio.ini file.

For example the code below defines the filter when building firmware for arduino environment.

[source]
----
    build_src_filter = +<arduino/>
----
==== {chapter}.{arch}.{counter:folder}. simulation
This folder contains the model file and command script that necessary to run flight gear as the 3D viewer.

All the files under the folder simulation/aircraft/arducopter are copied from the ArduCopter project.

// // // /////////////////////////////
// // // /////////////////////////////

